GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Jun's Stack",
    "author": "Jun Sung Lee",
    "url": "junsunglee.com"
}
